image: node:latest

stages:
  - build
  - test
  - deploy

build:
  before_script:
      - cd backend  
  stage: build
  script:
    - npm install
  artifacts:
    expire_in: 1 days
    when: on_success

test:
    before_script:
        - cd backend      
    stage: test
    coverage: /backend/
    dependencies:
        - build
    script:
        - npm test
    cache:
      paths:
      - coverage/
    artifacts:
        when: always

