image: node:latest

stages:
  - build
  - test
  - deploy

build:
  before_script:
      - cd backend  
  stage: build
  script:
    - npm install
  artifacts:
    expire_in: 1 days
    when: on_success

test:   
    stage: test
    coverage: /backend/
    dependencies:
        - build
    before_script:
      - yarn add --dev jest
    script:
        - npm test
    cache:
      paths:
      - coverage/
    artifacts:
        when: always
        reports:
            junit:
                - junit.xml
            cobertura: coverage/cobertura-coverage.xml

