image: node:latest

stages:
  - build
  - test
  - deploy

build:
  before_script:
    - cd backend
  stage: build
  script:
    - npm install
test:
before_script:
  - cd backend
  stage: test
  coverage: /backend/
  dependencies:
    - build
  script:
    - npm test
deploy:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."


